# This is a basic workflow to help you get started with Actions
name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Runs a single command using the runners shell
      - name: Begin
        run: echo Comenzando compilación de proyecto...

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      #- name: "Build Android project"
      #  uses: vgaidarji/android-github-actions-build@v1.0.1
      
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      # Runs a set of commands using the runners shell
      - name: "Run LS OUTPUT"
        run: ls -la app/build/outputs/apk/debug/
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 
          
      - name: UPLOAD Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@v1.0
        with:
          app_id: 1:342617603309:android:0e58a30314760c8cc4e0e4
          # Path of IPA or APK file to distribution.
          app_file: app/build/outputs/apk/debug/app-debug.apk 
          firebase_token: 1//036BhQWVQGrqVCgYIARAAGAMSNwF-L9IrRFM4qZIo1OWE5ji0qGIZVAv_y0hoTBnJe_BThhcU5I6Z3AQHkzQ-Cxlr3fV5SVN0S-w
          # Distribution groups
          tester_groups: Familia
          # Release notes for this build.
          release_notes: Nueva version
